### ISSUE TITLE
Invalid response body while trying to fetch

### ISSUE THREAD

**Issue by ogii** [CircleCI-Public/CircleCI-Env-Inspector#10]
When running the script:

```
? Enter your CircleCI API token [hidden]
? Enter your GitHub API token [hidden]
? Select an account ...orgnameredacted...
? Is this an Organization (Not a User)? Yes
```

Seeing the following error:

```
file:///project/node_modules/node-fetch/src/body.js:234
		const error_ = error instanceof FetchBaseError ? error : new FetchError(`Invalid response body while trying to fetch ${data.url}: ${error.message}`, 'system', error);
		                                                         ^

FetchError: Invalid response body while trying to fetch https://api.github.com/orgs/...redacted.../repos?per_page=100&page=2: Premature close
    at consumeBody (file:///project/node_modules/node-fetch/src/body.js:234:60)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Response.text (file:///project/node_modules/node-fetch/src/body.js:158:18)
    at async Response.json (file:///project/node_modules/node-fetch/src/body.js:148:16)
    at async getGitHubRepos (file:///project/index.js:116:19)
    at async file:///project/index.js:134:18 {
  type: 'system',
  errno: 'ERR_STREAM_PREMATURE_CLOSE',
  code: 'ERR_STREAM_PREMATURE_CLOSE',
  erroredSysCall: undefined
}

Node.js v19.3.0
```

When navigating directly to the url mentioned in the above error, I am getting the following response:

```
[

]
```

**Comment by EricRibeiro** [comment]
This might be because of the recursion strategy. #7 will potentially fix it.

**Comment by KyleTryon** [comment]
#7 is now merged. Please let us know if this is still happening for you. Thank you.

**Comment by KyleTryon** [comment]
#14 has been merged with additional improvements. Please let us know if you continue to experience any issues and we will re-open the thread
