### ISSUE TITLE
Node TypeError when running against an organization

### ISSUE THREAD

**Issue by vEpiphyte** [CircleCI-Public/CircleCI-Env-Inspector#2]
When running this against an organization, this produced a node error.

```
...
? Enter your CircleCI API token [hidden]
? Enter your GitHub API token [hidden]
? Select an account fooOrganization
? Is this an Organization (Not a User)? Yes
file:///project/index.js:149
USER_DATA.projects = repoData.filter((repo) => repo.variables.length > 0);
                                                              ^

TypeError: Cannot read properties of undefined (reading 'length')
    at file:///project/index.js:149:63
    at Array.filter (<anonymous>)
    at file:///project/index.js:149:31
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v19.3.0
```

**Comment by rstudner** [comment]
````
USER_DATA.projects = repoData.filter((repo) => {
  if (repo && repo.variables) {
    return repo.variables.length > 0;
  } else {
    return false;
  }
});
````
