### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by mziyut** [CircleCI-Public/CircleCI-Env-Inspector#9]
## What

It seems that variables in repoData are sometimes undefined

https://github.com/CircleCI-Public/CircleCI-Env-Inspector/blob/f234e25b5b68d453379ccf14bab34d82ce25aac5/index.js#L136-L149

### Log

```sh
file:///project/index.js:150
USER_DATA.projects = repoData.filter((repo) => repo.variables.length > 0);
                                                              ^

TypeError: Cannot read properties of undefined (reading 'length')
    at file:///project/index.js:150:63
    at Array.filter (<anonymous>)
    at file:///project/index.js:150:31
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v19.3.0
```

**Comment by mziyut** [comment]
I patched it and got around it.

```diff
diff --git a/index.js b/index.js
index 7bc2df2..5b3ce33 100644
--- a/index.js
+++ b/index.js
@@ -146,6 +146,6 @@ const repoData = await Promise.all(
     };
   })
 );
-USER_DATA.projects = repoData.filter((repo) => repo.variables.length > 0);
+USER_DATA.projects = repoData.filter((repo) => (repo.variables || []).length > 0);
 
 console.dir(USER_DATA, { depth: null });
```
